# Basic options
device: cpu  # Cuda device number, used for machine with multiple gpus
seed: null  # Whether fix the running seed to remove randomness
logfile: null  # Custom log file name

dataset:
  name: METRLA
  max_len: 1
  train_size: 1
  val_size: 0
  horizon: 36
  window: 72
  stride: 1
  delay: 0
  num_workers: 8  # Additional num of worker for data loading

train:
  batch_size: 1  # Total graph mini-batch size
  epochs: 300  # Maximal number of epochs
  lr: 3e-4  # Base learning rate
  lr_patience: 20  # number of steps before reduce learning rate
  lr_decay: 0.2  # learning rate decay factor
  monitor: train/loss  # Metric to monitor
  min_lr: 1.0e-5  # A lower bound on the learning rate.

  wd: 0.0  # L2 regularization, weight decay
  dropout: 0.0  # Dropout rate
  mlpmixer_dropout: 0.0  # Dropout rate for MLPMixer

model:
  gnn_type: GINEConv  # GNN type used, see core.model_utils.pyg_gnn_wrapper for all options
  gMHA_type: MLPMixer  # GraphMLPMixer or graph-based multihead attention: [MLPMixer, Hadamard, Standard, Graph, Addictive, Kernel]
  nfeatures_patch: 64  # Number of features for patch mixer
  nfeatures_node: 8  # Number of features for node mixer
  nlayer_gnn: 3  # Number of gnn layers
  nlayer_patch_mixer: 4  # Number of mlp mixer layers
  nlayer_node_mixer: 4  # Number of mlp mixer layers
  pool: mean  # Pooling type for generating graph/subgraph embedding from node embeddings
  residual: true  # Use residual connection

# Positional encoding options (currently not used directly, but needed for GraphPartitionTransform - TODO: Check and rm)
pos_enc:
  rw_dim: 16  # Random walk structural encoding
  lap_dim: 0  # Laplacian eigenvectors positional encoding
  patch_rw_dim: 8  # Patch random walk structural encoding
  patch_num_diff: -1  # Patch PE diffusion steps

# Metis patch extraction options
metis:
  enable: true  # Enable Metis partition (otherwise use random partition)
  online: false  # Enable data augmentation
  n_patches: 100  # The number of partitions
  num_hops: 1  # expanding patches with k hop neighbourhood
